### ISSUE TITLE
How to connect?

### ISSUE THREAD

**Issue by NoiseControllers** [nightwolf93/SlitherNET#1]
Hi, thanks by post this.

i would like know 
as I can connect

SlitherNet
https://gyazo.com/bdaac83a26d27e5cc82ccb8f40a7863b

client:
https://gyazo.com/2f7d700695bfd3f42103427a87e79772

**Comment by nightwolf93** [comment]
Default port in my server is 444

**Comment by NoiseControllers** [comment]
Nice ^^ good job
