### ISSUE TITLE
Error in connect (client)

### ISSUE THREAD

**Issue by ritney78** [nightwolf93/SlitherNET#2]
gameZ48fq.js:158 WebSocket connection to 'ws://localhost:444/slither' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I have a problem when I try to connect how to fix it?

Thanks

**Comment by circa94** [comment]
is your server running in port 444? Default should be 8080

**Comment by circa94** [comment]
make sure the port number is correct.

**Comment by nightwolf93** [comment]
Do you have any other application that run on this port ?

**Comment by ritney78** [comment]
yes it's work now thanks
